const theaterSeats = [
  {
    name: "Club",
    price: 200,
    seatsFilled: [
      [
        true,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        true,
        true,
        true,
        true,
        false,
      ],
      [
        false,
        false,
        true,
        true,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
      ],
    ],
  },
  {
    name: "Executive",
    price: 100,
    seatsFilled: [
      [true, true, true, false, false, true, false, false, false],
      [false, false, false, true, true, true, true, true, true],
      [false, false, false, false, false, false, false, false, false],
      [true, true, true, true, true, true, true, true, true],
      [
        false,
        false,
        false,
        false,
        true,
        true,
        true,
        false,
        false,
        false,
        true,
        false,
        true,
      ],
      [
        false,
        false,
        false,
        true,
        false,
        false,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
      ],
      [
        true,
        true,
        true,
        true,
        false,
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
      ],
    ],
  },
];

export default theaterSeats;
